import os
from typing import Union, Optional, Sequence, Iterator, List

class Molecule(Sequence[Atom]):
    def __init__(self, file: Union[str, bytes, os.PathLike[str]]): ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Atom: ...
    @property
    def id(self) -> Optional[str]: ...

class Atom:
    @property
    def serial(self) -> int: ...
    @property
    def altloc(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def residue_name(self) -> str: ...
    @property
    def residue_number(self) -> int: ...
    @property
    def segment(self) -> str: ...
    @property
    def element(self) -> str: ...
    @property
    def insertion_code(self) -> str: ...
    @property
    def chain_id(self) -> str: ...
    @property
    def occupancy(self) -> float: ...
    @property
    def temperature_factor(self) -> float: ...
    @property
    def charge(self) -> int: ...
    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...
    @property
    def z(self) -> float: ...

class Template:
    def __init__(self, name: str, file: Union[str, bytes, os.PathLike[str]]): ...
    def __len__(self) -> int: ...

class JessQuery(Iterator[Hit]):
    @property
    def jess(self) -> Jess: ...
    @property
    def molecule(self) -> Molecule: ...
    @property
    def ignore_chain(self) -> bool: ...
    @property
    def rmsd_threshold(self) -> float: ...
    @property
    def max_candidates(self) -> int: ...
    def __iter__(self) -> JessQuery: ...
    def __next__(self) -> Hit: ...

class Hit:
    @property
    def rmsd(self) -> float: ...
    @property
    def template(self) -> Template: ...
    @property
    def molecule(self) -> Molecule: ...
    @property
    def determinant(self) -> float: ...
    @property
    def log_evalue(self) -> float: ...
    @property
    def evalue(self) -> float: ...
    def atoms(self, transform: bool = True) -> List[Atom]: ...

class Jess:
    def __init__(self, templates: Iterable[Template]): ...
    def query(
        self,
        molecule: Molecule,
        rmsd_threshold: float,
        distance_cutoff: float,
        max_dynamic_distance: float,
        max_candidates: int = 1000,
        ignore_chain: bool = False,
    ) -> JessQuery: ...
